"""
Module to store the NATO dictionary for the nato_code package.
"""

# Dictionary of NATO phonetic code words for each letter
nato_codes = {
    "A": "ALFA",
    "B": "BRAVO",
    "C": "CHARLIE",
    "D": "DELTA",
    "E": "ECHO",
    "F": "FOXTROT",
    "G": "GOLF",
    "H": "HOTEL",
    "I": "INDIA",
    "J": "JULIET",
    "K": "KILO",
    "L": "LIMA",
    "M": "MIKE",
    "N": "NOVEMBER",
    "O": "OSCAR",
    "P": "PAPA",
    "Q": "QUEBEC",
    "R": "ROMEO",
    "S": "SIERRA",
    "T": "TANGO",
    "U": "UNIFORM",
    "V": "VICTOR",
    "W": "WHISKEY",
    "X": "X-RAY",
    "Y": "YANKEE",
    "Z": "ZULU",
    "0": "ZERO",
    "1": "ONE",
    "2": "TWO",
    "3": "THREE",
    "4": "FOUR",
    "5": "FIVE",
    "6": "SIX",
    "7": "SEVEN",
    "8": "EIGHT",
    "9": "NINE",
    "-": "DASH",
    ",": "COMMA",
    ".": "POINT",
    "@": "AT",
    "?": "QUESTMARK",
    "!": "EXCLAMARK",
    "'": "APOSTROPHE",
    '"': "QUOTMARK",
    "(": "LEFTPAREN",
    ")": "RIGHTPAREN",
    "&": "AMPERSAND",
    ":": "COLON",
    ";": "SEMICOLON",
    "/": "SLASH",
    "\\": "BACKSLASH",
    "+": "PLUS",
    "=": "EQUAL",
    "_": "UNDERSCORE",
    "$": "DOLLARSIGN",
    "%": "PERCENT",
    "#": "HASHTAG",
    "*": "ASTERISK",
    "<": "LESSTHAN",
    ">": "GREATERTHAN",
    "^": "CARET",
    "~": "TILDE",
    "`": "BACKTICK",
    "{": "LEFTCURLY",
    "}": "RIGHTCURLY",
    "[": "LEFTSQUARE",
    "]": "RIGHTSQUARE",
    "|": "PIPE",
    " ": " ",
    "\n": "\n",
    "\t": "\t",
}


def nato_code_words(codes: dict[str, str]) -> dict[str, str]:
    """Return the reverse of the key, value pairs in nato_codes for decode lookup"""
    words = {value: key for (key, value) in codes.items()}
    words["STOP"] = "."
    return words
